import "@/styles/globals.css";
import { Inter } from "next/font/google";
import {Poppins} from "next/font/google"
import ThirdWebContext from "@/context/ThirdWebContext";
import { TRPCReactProvider } from "@/trpc/react";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
  display: "swap",
});



export const metadata = {
  title: " Nexa Fund",
  description: "Generated by create-t3-app",
  icons: [
    {
      rel: "icon",
      url: "https://cdn.discordapp.com/attachments/1203013470300143616/1215723380716601384/UL.png?ex=65fdc9a1&is=65eb54a1&hm=03fc2939759fe24e5c2e6a98918f41e51d1cdf40b82a19040f523698a19b39c5&",
    },
  ],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>

        <TRPCReactProvider>
          <ThirdWebContext>{children}</ThirdWebContext>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
